import pygame

# Screen
BLACK = (0,0,0)
WHITE = (255,255,255)
SCREEN_SIZE = (800, 600)

# Game settings
# Player 1
PLAYER_ONE_INITIAL_X= 50
PLAYER_ONE_INITIAL_Y = 250
PLAYER_ONE_UP_KEY = pygame.K_w
PLAYER_ONE_DOWN_KEY = pygame.K_s
PLAYER_ONE_MOVEMENTS = [PLAYER_ONE_UP_KEY, PLAYER_ONE_DOWN_KEY]

# Player 2
PLAYER_TWO_INITIAL_X = 700
PLAYER_TWO_INITIAL_Y = 250
PLAYER_TWO_UP_KEY = pygame.K_UP
PLAYER_TWO_DOWN_KEY = pygame.K_DOWN
PLAYER_TWO_MOVEMENTS = [PLAYER_TWO_UP_KEY, PLAYER_TWO_DOWN_KEY]


# Players
PLAYER_WIDTH = 15
PLAYER_HEIGHT = 90
PLAYER_INITIAL_SPEED = 0
PLAYER_SPEED = 4
PLAYER_STOP = 0
PLAYERS_MOVEMENTS = PLAYER_ONE_MOVEMENTS + PLAYER_TWO_MOVEMENTS
UP_MOVEMENTS = [PLAYER_ONE_UP_KEY, PLAYER_TWO_UP_KEY]
DOWN_MOVEMENTS = [PLAYER_ONE_DOWN_KEY, PLAYER_TWO_DOWN_KEY]

# Ball
BALL_RADIUS = 10
BALL_INITIAL_X = 400
BALL_INITIAL_Y = 300
BALL_INITIAL_SPEED_X = 3
BALL_INITIAL_SPEED_Y = 3
BALL_SPEED = 1
